// <auto-generated />
using System;
using LinguiCards.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinguiCards.Infrastructure.Migrations
{
    [DbContext(typeof(LinguiCardsDbContext))]
    [Migration("20251231193536_AddDailyGoalByTranslationAndByGrammarToUserSettings")]
    partial class AddDailyGoalByTranslationAndByGrammarToUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinguiCards.Domain.Entities.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveTrainingSize")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyGoalByGrammar")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyGoalByTranslation")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyGoalXp")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveTrainingSize")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}

